apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: egudoc
  namespace: egudoc
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - egudoc.example.com
      secretName: egudoc-tls
  rules:
    - host: egudoc.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: egudoc
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: egudoc-frontend
                port:
                  name: http
